apiVersion: v1
kind: Service
metadata:
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo
